favicon_ico: /assets/images/favicon.ico
logo: /assets/images/logo.png
logo_with_title: true
title: Mosaico
description: Modelo comum para o desenho e desenvolvimento de serviços públicos digitais centrados nos cidadãos e empresas. 
theme: just-the-docs

has_toc: false
has_children: false

url: https://williamsartijose2023.github.io/ThemeJekyl/
gems:
  - jekyll-default-layout

sass:
  style: compressed
  sass_dir: _sass

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
