favicon_ico: /assets/images/favicon.ico
logo: /assets/images/logo.png
logo_with_title: true
title: Mosaico
description: Modelo comum para o desenho e desenvolvimento de serviços públicos digitais centrados nos cidadãos e empresas. 
theme: just-the-docs

url: https://williamsartijose2023.github.io/ThemeJekyl/
gems:
  - jekyll-default-layout

sass:
  style: compressed
  sass_dir: _sass
